Repository getspherelabs/anypass-kmp, pull requests merged in 2023-10, with the labels that each got.

#64 feat: Add new usecases to home middleware and reducer (#63)
  features/home/homeDomain/src/commonMain/kotlin/io/spherelabs/home/homedomain/GetPasswordsByCategory.kt
  features/home/homeDomain/src/commonMain/kotlin/io/spherelabs/home/homedomain/di/Koin.home.domain.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeEffect.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeMiddleware.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomePasswordUi.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeReducer.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeState.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeWish.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/di/Koin.home.presentation.kt
Labels: enhancement, hacktoberfest

#77 Fix FirebaseCore issue (#67)
  build-logic/convention/src/main/kotlin/io/getspherelabs/convention/multiplatform/MultiplatformExtension.kt
  core/admob/src/iosMain/kotlin/io/spherelabs/admob/GADBannerView.ios.kt
  core/common/build.gradle.kts
  core/common/src/androidMain/kotlin/io/spherelabs/common/Uuid.android.kt
  core/common/src/commonTest/kotlin/UuidTest.kt
  core/common/src/iosMain/kotlin/io/spherelabs/common/Uuid.ios.kt
  data/authManager/build.gradle.kts
  data/authManager/src/iosMain/kotlin/io/spherelabs/firebase/FirebaseAuthManager.ios.kt
  data/authManager/src/iosMain/kotlin/io/spherelabs/firebase/di/Koin.firebase.ios.kt
  gradle.properties
  shared/build.gradle.kts
Labels: bug, hacktoberfest

#88 Add strings module to resource module
  core/designsystem/build.gradle.kts
  core/designsystem/src/commonMain/kotlin/io/spherelabs/designsystem/fonts/Strings.kt
  resource/strings/build.gradle.kts
  resource/strings/src/androidMain/kotlin/io/spherelabs/resource/strings/Platform.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/EnAnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/KoAnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/RuAnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/UzAnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/strings/AnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/strings/Greeting.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/strings/Platform.kt
  resource/strings/src/iosMain/kotlin/io/spherelabs/resource/strings/Platform.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/account/AccountScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/addnewpassword/AddNewPassword.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/auth/SignInScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/auth/SignUpScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/generatepassword/CreatePasswordScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/home/HomeScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/onboarding/OnboardingScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/passphrase/MasterPasswordScreen.kt
  shared/src/commonMain/resources/MR/base/strings.xml
Labels: enhancement, hacktoberfest

#89 Add fetching profile and email in account screen
  data/local/src/commonMain/kotlin/io/spherelabs/data/local/di/Koin.local.kt
  data/local/src/commonMain/kotlin/io/spherelabs/data/local/mapper/UserMapper.kt
  data/local/src/commonMain/kotlin/io/spherelabs/data/local/repository/DefaultAccountRepository.kt
  data/local/src/commonMain/kotlin/io/spherelabs/data/local/repository/DefaultHomeRepository.kt
  data/local/src/commonTest/kotlin/io/spherelabs/data/local/AccountRepositoryTest.kt
  data/local/src/commonTest/kotlin/io/spherelabs/data/local/UserDaoTest.kt
  features/account/accountDomain/src/commonMain/kotlin/io/spherelabs/accountdomain/repository/AccountRepository.kt
  features/account/accountDomain/src/commonMain/kotlin/io/spherelabs/accountdomain/repository/AccountUserUi.kt
  features/account/accountDomain/src/commonMain/kotlin/io/spherelabs/accountdomain/repository/GetUser.kt
  features/account/accountDomain/src/commonMain/kotlin/io/spherelabs/accountdomain/repository/di/Koin.account.domain.kt
  features/account/accountPresentation/src/commonMain/kotlin/io/spherelabs/accountpresentation/AccountMiddleware.kt
  features/account/accountPresentation/src/commonMain/kotlin/io/spherelabs/accountpresentation/AccountReducer.kt
  features/account/accountPresentation/src/commonMain/kotlin/io/spherelabs/accountpresentation/AccountState.kt
  features/account/accountPresentation/src/commonMain/kotlin/io/spherelabs/accountpresentation/AccountWish.kt
  features/account/accountPresentation/src/commonMain/kotlin/io/spherelabs/accountpresentation/di/Koin.account.presentation.kt
  features/auth/authDomain/src/commonMain/kotlin/io/spherelabs/authdomain/HasCurrentUserExist.kt
  features/home/homeDomain/src/commonMain/kotlin/io/spherelabs/home/homedomain/GetEmail.kt
  features/home/homeDomain/src/commonMain/kotlin/io/spherelabs/home/homedomain/repository/HomeRepository.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/navigation/AnyPassNavHost.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/account/AccountScreen.kt
Labels: enhancement, hacktoberfest

#90 Use fingerprint feature in account module
  build-logic/convention/src/main/kotlin/io/getspherelabs/convention/multiplatform/MultiplatformExtension.kt
  build-logic/settings.gradle.kts
  core/designsystem/build.gradle.kts
  features/masterpassword/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/di/Koin.masterpassword.domain.kt
  features/masterpassword/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordMiddleware.kt
  features/masterpassword/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordReducer.kt
  features/masterpassword/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordState.kt
  features/masterpassword/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordWish.kt
  features/passphrase/masterPasswordDomain/build.gradle.kts
  features/passphrase/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/GetFingerprintStatus.kt
  features/passphrase/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/GetMasterPassword.kt
  features/passphrase/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/IsPasswordExist.kt
  features/passphrase/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/SetMasterPassword.kt
  features/passphrase/masterPasswordDomain/src/commonMain/kotlin/io/spherelabs/masterpassworddomain/di/Koin.masterpassword.domain.kt
  features/passphrase/masterPasswordPresentation/build.gradle.kts
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordEffect.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordMiddleware.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordReducer.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordState.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordViewModel.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/MasterPasswordWish.kt
  features/passphrase/masterPasswordPresentation/src/commonMain/kotlin/io/spherelabs/masterpasswordpresentation/di/Koin.masterpassword.presentation.kt
  features/passphrase/masterPasswordPresentation/src/commonTest/kotlin/MasterPasswordReducerTest.kt
  gradle/libs.versions.toml
  manager/biometry/build.gradle.kts
  manager/biometry/src/iosMain/kotlin/io/spherelabs/biometry/BiometricManager.kt
  manager/biometry/src/iosMain/kotlin/io/spherelabs/biometry/Coroutine.kt
  settings.gradle.kts
  shared/build.gradle.kts
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/home/HomeScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/passphrase/MasterPasswordScreen.kt
  shared/src/commonMain/resources/MR/base/strings.xml
Labels: hacktoberfest

#95 Fix fonts module in `iosApp`
  core/analytics/src/androidMain/kotlin/io/spherelabs/analytics/Platform.android.kt
  core/analytics/src/commonMain/kotlin/io/spherelabs/analytics/Greeting.kt
  core/analytics/src/commonMain/kotlin/io/spherelabs/analytics/Platform.kt
  core/analytics/src/iosMain/kotlin/io/spherelabs/analytics/Platform.ios.kt
  data/local/build.gradle.kts
  gradle.properties
  iosApp/iosApp/Info.plist
  manager/biometry/build.gradle.kts
  manager/biometry/src/iosMain/kotlin/io/spherelabs/biometry/Coroutine.kt
  resource/fonts/build.gradle.kts
  resource/fonts/src/androidMain/kotlin/io/spherelabs/resource/fonts/Fonts.android.kt
  resource/fonts/src/commonMain/kotlin/io/spherelabs/resource/fonts/Fonts.common.kt
  resource/fonts/src/iosMain/kotlin/io/spherelabs/resource/fonts/Fonts.ios.kt
  resource/icons/build.gradle.kts
  shared/build.gradle.kts
Labels: bug, hacktoberfest

#97 Add version catalog extensions (#94)
  androidApp/build.gradle.kts
  build-logic/convention/src/main/kotlin/io/getspherelabs/convention/multiplatform/MultiplatformExtension.kt
  build-logic/convention/src/main/kotlin/io/getspherelabs/convention/multiplatform/VersionCatalogExtension.kt
  build.gradle.kts
  core/admob/build.gradle.kts
  core/common/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/validation/build.gradle.kts
  data/authManager/build.gradle.kts
  data/local/build.gradle.kts
  data/prefs/build.gradle.kts
  features/account/accountDomain/build.gradle.kts
  features/account/accountPresentation/build.gradle.kts
  features/addnewpassword/addNewPasswodPresentation/build.gradle.kts
  features/addnewpassword/addNewPasswordDomain/build.gradle.kts
  features/auth/authDomain/build.gradle.kts
  features/auth/authPresentation/build.gradle.kts
  features/generatepassword/generatePasswordDomain/build.gradle.kts
  features/generatepassword/generatePasswordPresentation/build.gradle.kts
  features/home/homeDomain/build.gradle.kts
  features/onboarding/onboardingDomain/build.gradle.kts
  features/onboarding/onboardingPresentation/build.gradle.kts
  features/passphrase/masterPasswordDomain/build.gradle.kts
  features/passphrase/masterPasswordPresentation/build.gradle.kts
  gradle/libs.versions.toml
  manager/biometry/build.gradle.kts
  manager/password/build.gradle.kts
  navigation/build.gradle.kts
  resource/strings/build.gradle.kts
  shared/build.gradle.kts
Labels: enhancement, hacktoberfest

#110 Add validation check when add new passwords
  androidApp/src/main/AndroidManifest.xml
  core/designsystem/src/commonMain/kotlin/io/spherelabs/designsystem/button/LKButton.kt
  core/designsystem/src/commonMain/kotlin/io/spherelabs/designsystem/passwordcard/LKPasswordCardTokens.kt
  core/designsystem/src/commonMain/kotlin/io/spherelabs/designsystem/textfield/LKTextField.kt
  core/mlkit/build.gradle.kts
  core/mlkit/src/androidMain/kotlin/io/spherelabs/mlkit/Platform.kt
  core/mlkit/src/commonMain/kotlin/io/spherelabs/mlkit/Greeting.kt
  core/mlkit/src/commonMain/kotlin/io/spherelabs/mlkit/Platform.kt
  core/mlkit/src/iosMain/kotlin/io/spherelabs/mlkit/Platform.kt
  core/validation/src/commonMain/kotlin/io/spherelabs/validation/PasswordValidation.kt
  core/validation/src/commonMain/kotlin/io/spherelabs/validation/WebsiteValidation.kt
  features/addnewpassword/addNewPasswodPresentation/build.gradle.kts
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordMiddleware.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordReducer.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordState.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordValidateMiddleware.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordViewModel.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/AddNewPasswordWish.kt
  features/addnewpassword/addNewPasswodPresentation/src/commonMain/kotlin/io/spherelabs/addnewpasswodpresentation/di/Koin.addnewpassword.presentation.kt
  features/auth/authPresentation/src/commonMain/kotlin/io/spherelabs/authpresentation/signup/SignUpValidateMiddleware.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeEffect.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeReducer.kt
  features/home/homePresentation/src/commonMain/kotlin/io/spherelabs/home/homepresentation/HomeWish.kt
  gradle/libs.versions.toml
  manager/otp/build.gradle.kts
  manager/otp/src/commonMain/kotlin/io/spherelabs/otp/Otp.kt
  manager/otp/src/commonMain/kotlin/io/spherelabs/otp/OtpDuration.kt
  manager/otp/src/commonMain/kotlin/io/spherelabs/otp/OtpManager.kt
  manager/otp/src/commonTest/kotlin/OtpManagerTest.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/Composer.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/LockerStack.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/NavigationController.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/impl/NavHostScopeImpl.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/impl/NavigationControllerImpl.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/stack/NavigationStack.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/stack/Stack.kt
  navigation/src/commonMain/kotlin/io/spherelabs/navigation/stack/StackSaver.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/EnAnyPassStrings.kt
  resource/strings/src/commonMain/kotlin/io/spherelabs/resource/strings/AnyPassStrings.kt
  settings.gradle.kts
  shared/src/commonMain/kotlin/io/spherelabs/anypass/navigation/AnyPassNavHost.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/navigation/Route.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/navigation/Saveable.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/account/navigation/AccountNavigation.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/addnewpassword/AddNewPassword.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/addnewpassword/AddNewPasswordScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/addnewpassword/navigation/AddNewPasswordNavigation.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/generatepassword/CreatePasswordScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/generatepassword/navigation/CreatePasswordNavigation.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/home/HomeScreen.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/home/navigation/HomeNavigation.kt
  shared/src/commonMain/kotlin/io/spherelabs/anypass/ui/keypassword/navigation/KeyPasswordNavigation.kt
  shared/src/commonMain/resources/MR/images/chart.svg
  shared/src/commonMain/resources/MR/images/discord.svg
  shared/src/commonMain/resources/MR/images/dribble.svg
  shared/src/commonMain/resources/MR/images/linkedin.svg
  shared/src/commonMain/resources/MR/images/messenger.svg
  shared/src/commonMain/resources/MR/images/patreon.svg
Labels: enhancement

#136 add add auth domain architecture test #129
  features/addnewpassword/addNewPasswordDomain/src/androidUnitTest/kotlin/AddNewPasswordDomainArchitectureTest.kt
  features/auth/authDomain/build.gradle.kts
  features/auth/authDomain/src/androidUnitTest/kotlin/AddNewAuthDomainArchitectureTest.kt
Labels: good first issue, hacktoberfest

#140 Add spotify-ruler (#121)
  gradle/libs.versions.toml
Labels: good first issue, hacktoberfest
